theme: jekyll-theme-minimal
title: Welcome to Katherine Leyonmark's Homepage!
description: A comprehensive location to learn about me and my work.
![Profile Image](file:///home/leyonmarkk/Downloads/websitepic.jpg)
