theme: jekyll-theme-minimal
title: Katherine Leyonmark
<img src="/websitepic.jpg" alt="Profile Photo" style="width:128px;height:128px;"> 
description: A comprehensive location to learn about me and my work.
